package io.github.matyrobbrt.eventdispatcher.internal.asm.annotation;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.objectweb.asm.Type;

import static java.lang.annotation.ElementType.TYPE;

/**
 * Indicates that a type has been generated by a ASM Listener generator for
 * subscribing to events.
 */
@Retention(RetentionPolicy.CLASS)
@Target(TYPE)
public @interface ASMGeneratedEventListener {

	public static final String DESCRIPTOR = Type.getInternalName(ASMGeneratedEventListener.class);

}
